services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_PORT:-65081}:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      PMA_PORT: "${DB_PORT}"
    depends_on:
      - mysql
    networks:
      - sail